# Generated by Django 2.2.5 on 2020-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_src', models.CharField(max_length=255)),
                ('ban_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
