# Generated by Django 2.2.5 on 2020-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopagetemplateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='ban_img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
