# Generated by Django 2.2.5 on 2020-06-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopagetemplateapp', '0002_auto_20200606_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='ban_src',
        ),
    ]
