# Generated by Django 2.2.5 on 2020-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopagetemplateapp', '0003_remove_banner_ban_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ban_placeholder',
            field=models.CharField(default='pl1', max_length=3),
        ),
    ]
