# Generated by Django 2.2.5 on 2020-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopagetemplateapp', '0004_banner_ban_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ban_name',
            field=models.CharField(default='banne_name', max_length=255),
        ),
    ]
